version: "3.9"
services:
  db:
    image: mysql:8.0
    env_file:
      - ./environments/db.env
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    environment:
      RAILS_ENV: production
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp:cached
      - /var/www/cap-dp-tutorial/shared:/var/www/cap-dp-tutorial/shared
      - bundle_mini:/usr/local/bundle
      - node_modules_mini:/myapp/node_modules
      - tmp-data_mini:/myapp/tmp
      - public-data_mini:/myapp/public
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    name: mysql-data
    driver: local
  bundle_mini:
    name: bundle_mini
  node_modules_mini:
    name: node_modules_mini
  tmp-data_mini:
    name: tmp-data_mini
  public-data_mini:
    name: public-data_mini
